### ISSUE TITLE
test  result is bad!

### ISSUE THREAD

**Issue by c1a1o1** [sagiebenaim/OneShotTranslation#3]
test.py  --dataroot=./datasets/facades/ --name=facades_ost --model=ost --load_dir=facades_ost --no_dropout --n_downsampling=2 --num_unshared=2 --start=0 --max_items_A=12

**Comment by sagiebenaim** [comment]
I cannot understand your error from this message, can you describe what you ran? What did you get? Thanks

**Comment by c1a1o1** [comment]
I use the cat2dog   dataset  from  http://vllab.ucmerced.edu/hylee/DRIT/datasets/cat2dog.zip

**Comment by sagiebenaim** [comment]
With a new dataset which is not supported here, you'll need to adjust number of sharing layers and possibly the architecture.
