### ISSUE TITLE
Some questions about the metrics in your paper

### ISSUE THREAD

**Issue by rockeyben** [sagiebenaim/OneShotTranslation#5]
Hi, I have been working on another image translation task and I am interested in the metrics in your paper: **perceptual distance** & **style distance**. Can you provide some details about the evaluation? Cause if I use the [popular vgg16 model on github](https://github.com/machrisaa/tensorflow-vgg), then the input will be in range [0, 255], so the style distance will be around 10k -20k, I am wandering did you use a customized vgg whose input is in range [0, 1] so that the distance could be around 1-10?
Thanks

**Comment by sagiebenaim** [comment]
Hi, we used a similar vgg model and simply normalized the values before taking to distance so that distance is around 1 to 10. So instead of using a customized model you can simply normalize before taking the distance.

**Comment by rockeyben** [comment]
Thanks for your reply :D
